version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: acoustic_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: acoustic_data
    ports:
      - "5433:5432"
    volumes:
      # Папка 'db_data' буде створена в корені поруч із цим файлом
      - ./db_data:/var/lib/postgresql/data

# Опціонально: додайте це, якщо хочете бачити дані в VS Code через volume
volumes:
  db_data: